stages:
  - build
  - scan
  - deploy
  - security
  - notify

variables:
  IMAGE_NAME: registry.local/backend
  HELM_RELEASE: backend

# ---------- BUILD ----------
build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA services/backend
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA

# ---------- SCANS ----------
trivy:
  stage: scan
  script:
    - trivy image --exit-code 1 $IMAGE_NAME:$CI_COMMIT_SHA

sonarqube:
  stage: scan
  script:
    - sonar-scanner

# ---------- DEPLOY DEV ----------
deploy_dev:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  script:
    - kubectl apply -f platform/kubernetes/network-policies/
    - helm upgrade --install $HELM_RELEASE platform/helm/backend \
        --namespace dev --create-namespace \
        --set image.tag=$CI_COMMIT_SHA

# ---------- DEPLOY PROD ----------
deploy_prod:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  when: manual
  script:
    - kubectl apply -f platform/kubernetes/network-policies/
    - helm upgrade --install $HELM_RELEASE platform/helm/backend \
        --namespace prod --create-namespace \
        --set image.tag=$CI_COMMIT_SHA

# ---------- ROLLBACK ----------
rollback:
  stage: security
  when: on_failure
  script:
    - helm rollback $HELM_RELEASE

# ---------- NOTIFY ----------
notify_failure:
  stage: notify
  when: on_failure
  script: |
    curl -H "Content-Type: application/json" \
    -d "{\"text\":\" Deploy fallido. Rollback ejecutado. Revisa NetworkPolicies.\"}" \
    $TEAMS_WEBHOOK_URL
